[project]
name = "make-gist-list"
version = "1.0.0"
description = "Create a markdown list of your public GitHub gists and updates a gist with that list."
requires-python = ">=3.10"
dependencies = ["requests>=2.32.0"]

[project.scripts]
make-gist-list = "make_gist_list:main"
